<?php
return array(
	'title'      => esc_html__( 'Logo Setting', 'jixic' ),
	'id'         => 'logo_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'       => 'image_favicon',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Favicon', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site favicon image', 'jixic' ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Home One Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Normal Logo', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site normal logo image', 'jixic' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Two Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo2',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Two Logo', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site Home Two logo image', 'jixic' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension2',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
            'id' => 'normal_logo_show3',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Three Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo3',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Three Logo', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site Home Three logo image', 'jixic' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension3',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
            'id' => 'normal_logo_show4',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Four Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo4',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Four Logo', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site Home Four logo image', 'jixic' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension4',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
            'id' => 'normal_logo_show5',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Five Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo5',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Five Logo', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site Home Five logo image', 'jixic' ),
			'required' => array( 'normal_logo_show5', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension5',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show5', '=', true ),
		),
		array(
            'id' => 'normal_logo_show6',
            'type' => 'switch',
            'title' => esc_html__('Enable Six Logo', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo6',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo Six', 'jixic' ),
			'subtitle' => esc_html__( 'Insert logo Six image', 'jixic' ),
			'required' => array( 'normal_logo_show6', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension6',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show6', '=', true ),
		),
		array(
            'id' => 'normal_logo_show7',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo Seven', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo7',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo Seven', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site logo Seven image', 'jixic' ),
			'required' => array( 'normal_logo_show7', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension7',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show7', '=', true ),
		),
		array(
            'id' => 'normal_logo_show8',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo Eight', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo8',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo Eight', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site logo Eight image', 'jixic' ),
			'required' => array( 'normal_logo_show8', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension8',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show8', '=', true ),
		),
		array(
            'id' => 'normal_logo_show9',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo Nine', 'jixic'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo9',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo Nine', 'jixic' ),
			'subtitle' => esc_html__( 'Insert site logo Nine image', 'jixic' ),
			'required' => array( 'normal_logo_show9', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension9',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Normal Logo Dimentions', 'jixic' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'jixic' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show9', '=', true ),
		),
		array(
			'id'       => 'logo_settings_section_end',
			'type'     => 'section',
			'indent'      => false,
		),
	),
);
